taskcluster/taskcluster-queue

Vagrantfile, bin/server.js, npm-shrinkwrap.json, package.json, queue/blobstore.js, queue/queueservice.js, routes/api/v1.js, schemas/pending-tasks-response.yml, schemas/poll-task-urls-response.yml, schemas/task.yml, test/api/claimtask_test.js, test/api/polltask_test.js, test/api/querytasks_test.js, test/queue/queue_test.js
* Marked everything deprecated accordingly
* Updated JSON schemas to match what we will have in the future
Shouldn't break compatibility, but allow migration to the new poll-flow, as documented:
http://docs.taskcluster.net/queue/worker-interaction/
=> Backport pollflow

routes/api/artifacts.js, schemas/list-artifacts-response.yml
Hey Jonas,
I believe these commits fix some very minor issues.
1) For consistency I wanted to add the "object" type to list-artifacts-response.yml where it was not explicitly stated, as this was the only place where it wasn't (I only noticed when I hit a problem parsing).
2) The other tweak is adding the # character to the end of some of the Input and Output url json schema references. I haven't tested the code change, but I am hoping that will fix e.g. lines 267-268 in http://references.taskcluster.net/queue/v1/api.json:
```
267       "input": "http://schemas.taskcluster.net/queue/v1/post-artifact-request.json",
268       "output": "http://schemas.taskcluster.net/queue/v1/post-artifact-response.json"
```
to be consistent with the other references, e.g.:
```
22       "input": …
```
=> Minor tweaks!

queue/deadlineresolver.js, routes/v1.js, schemas/task-status.yml, test/api/canceltask_test.js, test/api/deadline_test.js
From [bug 1148965](https://bugzilla.mozilla.org/show_bug.cgi?id=1148965).
>   A) Set {reasonCreated: 'exception'}, if a run was created solely for one of the two cases:
1) task canceled before first run was scheduled
2) deadline expired before first run was schedule
=> Use  for exception run

routes/artifacts.js, test/api/artifact_test.js
Allow artifact creation past task resolution if resolved as `exception`.
Generally, tasks resolved as exception aren't being resolved in a calm and orderly fashion, and any resulting artifact or log is a best-effort service.
=> Allow artifact creation past resolution as exception

bin/expire-queues.js, config/test.js, package.json, queue/queueservice.js, routes/v1.js, test/api/expirequeues_test.js, test/api/helper.js, test/queue/queueservice_test.js, test/runtests.sh
This address two bugs:
https://bugzilla.mozilla.org/show_bug.cgi?id=1170821
https://bugzilla.mozilla.org/show_bug.cgi?id=1162943
Once this is rolled out, we give it a week or a few days, and then remove all the legacy queues. So that pull URLs again returns an array of one queue.
For now we abuse the list returned for priority, to migrate underlying queue names to a new name without dropping tasks.
=> Fix queue collisions

routes/artifacts.js, test/api/artifact_test.js
When a request is made to update an artifact, details about the original
as well as the new artifact should be included in the error response
when the artifact can not be updated.
=> Error response should include artifact details

queue/deadlineresolver.js
Avoid duplicate messages for exceptions after deadline... We should only report the messages if `deadline-exceeded` is the reason.
If it was cancelled, or something else... we should publish another message about that.
----
Note, this is not a violation of our promises... messages are at-least once, so delivering them an extra time a few hours later is technically okay (but not elegant). And in practice we consider it a bug.
=> Fix extra exception messages after deadline

routes/v1.js, schemas/constants.js
Using `^[A-Za-z0-9_-]{8}[Q-T][A-Za-z0-9_-][CGKOSWaeimquy26-][A-Za-z0-9_-]{10}[AQgw]$`
Explanation
---------------
UUID v4 is a 128 bit scheme (below numbered 0-127), with the following six fixed bits:
* bit 48: `0`
* bit 49: `1`
* bit 50: `0`
* bit 51: `0`
* bit 64: `1`
* bit 65: `0`
Splitting this into groups of 6 bits to see the character boundaries, we get:
```
position:                                                                                                                 11 111111 111111 111111 111111 11
11 111111 112222 222222 333333 333344 444444 445555 555555 666666 666677 777777 778888 888888 999999 999900 000000 001111 111111 222222 22
012345 678901 234567 890123 456789 012345 678901 234567 890123 456789 012345 678901 234567 890123 456789 012345 678901 234567 890123 …
```
=> Updated slugid pattern to enforce uuid v4 compliance

schemas/constants.js, schemas/create-task-request.yml, schemas/task.yml
I can make similar changes for all components -- but would it be better to define a scope (and scopelist, scopeset, etc.) in taskcluster-base, and refer to that schema from elsewhere?
=> Bug 1193607: update schema for limite scope charset

schemas/post-artifact-response.yml
Last one that was missing. Note, I hadn't spotted it before due to [bug 1221239](https://bugzilla.mozilla.org/show_bug.cgi?id=1221239). So this should really be the last "missing type" fix. I'll also see if I can update the schema to make sure we catch these automatically in future during validation.
P.S. This was so small, I didn't create a bugzilla bug for it.
=> Added missing type

README.md, routes/v1.js, schemas/create-task-request.yml
The docs didn't consistently define which scopes are required by a task submitter due to entries in the task definition payload.
I'd like to introduce consistent wording so that it is simple to have an overview of which scopes you require for submitting any particular task definition.
=> Bug 1221132 - improve wording

routes/artifacts.js, routes/v1.js, test/api/artifact_test.js
Got rid of all the `assume:` scopes...
Well, I left them in for keeping compatibility...
IMO, the big non-trivial thing we have to move here is:
`defineTask` and `createTask`, those are called by clients directly or through scheduler... We need those to move to the new scopes, and remove the legacy scopes.
Once that is done, the road is pretty open for API end-points to list tasks by `taskGroupId` and implementation of new big graph scheduler.
=> Bug 1228012: Deprecate all assume: scopes in API endpoints

routes/v1.js, test/api/helper.js, test/api/reruntask_test.js
This replaces our first ```res.status()``` with the new ```res.reportError()```. More will follow if this works.
=> Update to new errors

routes/v1.js
The only places that the old-style is left is in artifacts.js
```
$ git grep res\.status ./routes/
routes/artifacts.js:    return res.status(400).json({
routes/artifacts.js:    return res.status(404).json({
routes/artifacts.js:    return res.status(404).json({
routes/artifacts.js:    return res.status(400).json({
routes/artifacts.js:      return res.status(409).json({
routes/artifacts.js:      return res.status(409).json({
routes/artifacts.js:      return res.status(409).json({
routes/artifacts.js:    return res.status(404).json({
routes/artifacts.js:    return res.status(403).json({
routes/artifacts.js:    return res.status(404).json({
routes/artifacts.js:    return res.status(404).json({
routes/artifacts.js:    return res.status(412).json({
routes/artifacts.js:    return …
```
=> Update to all new-style errors in v1.js

routes/artifacts.js, schemas/list-artifacts-response.yml, schemas/list-task-group-response.yml, test/api/artifact_test.js
I don't think this breaks anything....
Query string parameters are optional, so old client will just keep on working as they do now :)
Notice that I didn't have to modify the old tests, just add a new test case.
right now we list up to 10k without continuation token... After this we'll only be able to list up to 1k without continuation token... But with continuation token we'll be unbounded...
I doubt anyone has more than 1k artifacts anyways... So this should do fine :)
=> Employ continuationToken for listArtifact

src/api.js
We don't need at-least one run anymore as createTask with task.dependencies as a self-loop is the same as defineTask, so no distinction
=> bug 1275326 fix createTask idempotency

src/api.js
I'm basing this determination on checks made in the `dependencyTracker`.
=> Must create tasks after their dependencies

src/dependencyresolver.js
Now we can make an alert in signalfx.. if we check that the loop counter is always above > 0.
This is similar to what jhford is doing with deadmansswitch...
=> Count poll-loop cycles

.eslintrc, README.md, npm-shrinkwrap.json, package.json, src/api.js, src/artifacts.js, src/bucket.js, src/claimresolver.js, src/data.js, src/deadlineresolver.js, src/dependencyresolver.js, src/main.js, src/queueservice.js, test/bucket_test.js, test/lint_test.js, test/queueservice_test.js
I'll enable the lint test and fix issues with it later...
=> More monitor

src/claimresolver.js, src/deadlineresolver.js, src/dependencyresolver.js
Some stats to see if claimResolvers work queue reaches zero... If it doesn't that explains why @lundjordan saw a task in state `running` 14 hours after `takenUntil` expired.
=> Count when work queues reach zero

config.yml, src/api.js, src/artifacts.js, src/main.js
Since we're no longer considering the useCloudMirror flag in the task, let's not bother loading it any longer.  This removes some more s3-copy-proxy leftovers and cleans up the configs.  It also adds eu-central-1 to the list of regions that we rewrite urls for, since we now have this regions in cloud-mirror
@jonasfj, I don't have a full test environment for this, can you double check that it looks OK?
=> bug 1285506 -- let queue rewrite urls for eu-central-1

schemas/constants.yml, schemas/create-task-request.yml, schemas/task.yml
The description of task expiration looks like it's missing 'task' in the
sentence: "Notice that all artifacts for the must have an expiration that is no
later than this."
=> Description of task expiraiton has a missing word.

src/exchanges.js, test/taskgroup_test.js
Also make schedulerId mandatory for task-group-resolved messages while I'm in here.
=> Add inverse test for task group resolved

src/artifacts.js, src/main.js
Should be a partial fix for https://bugzilla.mozilla.org/show_bug.cgi?id=1306040
Basically we need to resolve region for us-west-2, otherwise we never go here:
https://github.com/taskcluster/taskcluster-queue/blob/8e9a186726233904457dbac429074a5954a6fbd3/src/artifacts.js#L358-L359
=> Always resolve canonical region

src/queueservice.js
Once this is deployed we can modify the claimWork logic to ensure that we record the hintId for each claim...
Notably we can use this ensure that two different azure messages doesn't lead to the same task being claimed twice by the same worker (when there is a duplication of azure messages)...
Note: this could break workers if they won't ignore extra properties...
@petemoore ^ do you know if additional properties will break generic-worker, I doubt it.. but it would be hard to back out...
=> Added hintId to all pending azure queue messages

docs/task-schema.md
This isn't optimal.  Before https://github.com/taskcluster/taskcluster-docs/pull/142/commits/ea7386919b925e1f39f2a3cdbdf8d76043d12bc4, there was an extra API reference page like this one showing just the task schema.  tc-lib-docs doesn't provide a way to include such a thing.  So we'll put it under docs.
I'm not sure this will actually work, but we'll find out.
=> add schema docs

package.json, yarn.lock
We're using a really ancient version of the babel-preset.  I'm not sure why, but maybe we should update it to the latest.
=> Use the same babel-preset that we're using elsewhere

.travis.yml, config.yml, package.json, src/main.js, yarn.lock
As we discussed in irc. Auth already manages the production tc-queue azure tablestore account, so we should be safe to deploy there once I add this env var to tc-queue config. I expect these tests will fail right now because of the nodejs.org issue, but I'll rerun them tomorrow and then we can think about landing this.
=> Change azure tables auth mechanism

config.yml
in anticipation of increased load for g2.2xlarge (gecko-t-win7-32-gpu, gecko-t-win10-64-gpu worker types) enable instance instantiation in us-east-2 to mitigate cost and availability issues
=> bug 1318648 - support instance instantiation in us-east-2

src/workclaimer.js
This should set the clientId to something like `task-client/HpkPAF3GTkSfA9oxHSHIKQ/0/on/us-west-1/i-09ba01b87daecb599/at/1492905600`.  The `at` part is there so we can debug workers using expired credentials.  I wouldn't mind leaving that off, it just means we'll create a lot of creds with the same clientId.
=> Set clientId for claimed-task temporary creds

src/artifacts.js
https://sentry.prod.mozaws.net/operations/taskcluster-queue/issues/608950/
Not sure this is the correct fix, but it does handle the case this failed for. It was trying to access `workerGroup` and `workerId` for run 2 of the following:
```
{
"status": {
"taskId": "9phwiB_TSG2oMcD1Kkjbqg",
"provisionerId": "buildbot-bridge",
"workerType": "buildbot-bridge",
"schedulerId": "task-graph-scheduler",
"taskGroupId": "lkJdznr3QDyZdELDnQnwGA",
"deadline": "2017-05-29T22:38:06.113Z",
"expires": "3017-05-25T22:38:06.187Z",
"retriesLeft": 5,
"state": "exception",
"runs": [
{
"runId": 0,
"state": "failed",
"reasonCreated": "scheduled",
"reasonResolved": "failed",
"workerGroup": "buildbot-bridge",
"workerId": "buildbot-bridge",
"takenUntil": "2017-05-25T23:10:03.219Z",
"scheduled": …
```
=> Fix artifacts for runs that have been cancelled

schemas/create-task-request.yml
This is only on the create task request, not on the response since that would break what we currently have stored in the queue.
=> Limit task.routes to 10

schemas/create-task-request.yml
Reverts taskcluster/taskcluster-queue#151
At request of @escapewindow temporarily reverted limit of routes to 10.
=> Revert "Limit task.routes to 10"

src/artifacts.js
Artifact expiry can match task expiry (artifacts don't need to expire *before* task).
=> API error message fix for createArtifact

docs/superseding.md
(mostly copied from docker-worker docs)
=> Bug 1397373 - describe superseding in queue reference

schemas/list-workers-response.yml, src/api.js, test/workerinfo_test.js
This PR is currently blocked by https://github.com/taskcluster/azure-entities/pull/30. Once that is merged, I will need to update azure-entities version.
=> Bug 1401206 - Extend the list of workers endpoint

schemas/list-workers-response.yml, schemas/worker-response.yml, src/api.js, src/data.js, src/workerinfo.js, test/workerinfo_test.js
Use `Entity.types.JSON` with `[{taskId, runId}, ...]` instead of `Entity.types.SlugIdArray`.
=> Bug 1404010 - Extend the worker to have the runId of its most recentTask

schemas/post-artifact-response.yml
This is important because it's making implementing taskcluster-lib-artifact-go harder
=> Fix a typo in schema

src/api.js
https://sentry.prod.mozaws.net/operations/taskcluster-queue/issues/678220/
```
Error: DateType 'expires' expected a date got type: string
```
=> Bug 1407037 - cast expires to a Date

src/api.js
I assume this was a typo in the initial implementation...
@helfi92, if this is used by any workers we might have re-issue the scope...
But I don't see anything here: https://tools.taskcluster.net/auth/scopes
so we can probably just deploy...
=> Fix declareWorker scope

schemas/list-artifacts-response.yml
Turns out this schema was missed.  Causes issues in the tools site
=> Add blob storageType to the list artifact response

package.json, schemas/post-artifact-response.yml, yarn.lock
This is a subtle bug that's only caught in a statically, strongly typed language.  Basically, the header properties of single part uploads is a mapping of strings to strings, but for multi part is a mapping of strings to json-typed data (e.g. a number is a number, not converted to string).
Not having this makes the go lib-artifact library a lot more difficult to implement.
The difference between 3.0.0 and 2.0.0 of remotely signed s3 is pretty trivial: https://github.com/taskcluster/remotely-signed-s3/commit/1d7cfe3db4e2129cc7d5659d117818dbedda6e79
If you're OK with this change, I think it's a small enough change that it shouldn't effect the change freeze because it's a minor additive change that only touches code which a) doesn't crash the queue if it fails and b) only touches blob …
=> Correctly send all headers as strings

schemas/constants.yml, schemas/list-provisioners-response.yml, schemas/list-workers-response.yml, schemas/list-workertypes-response.yml, schemas/provisioner-response.yml, schemas/update-provisioner-request.yml, schemas/workertype-response.yml, test/workerinfo_test.js
The best option here is to switch actions back to allowing substitution in the URL path. This pull-request modifies the action explanations to talk about path parameters.
=> Modify action explanations to reflect path parameters

docs/actions.md, docs/superseding.md, docs/task-life-cycle.md, docs/task-schema.md, docs/worker-hierarchy.md, docs/worker-interaction.md
This
* defines the provisioner / worker-type / worker hierarchy a little
better
* distinguishes queue actions from task actions
* removes specific reference to the tools UI views
* gives more detail on how calls can occur from automation, including
use of the `name` property
It presupposes some planned changes to the queue APIs; in particular,
that actions be returned from the getXxx methods and not from the
listXxx methods.
=> Expand Queue Actions documentation

schemas/list-workers-response.yml, schemas/list-workertypes-response.yml, src/api.js, test/workerinfo_test.js
Actions are not needed when listing workers or worker-types. When a worker-type requests a list of workers for example, the worker-type will then need to make a request to `getWorkerType()` to get the list of actions with  `context=worker-type`.
=> Remove actions when listing workerTypes and workers

schemas/list-workers-response.yml, src/api.js, test/workerinfo_test.js
Hi @helfi92,
Although it is entirely valid to specify `type` as the array `["string", "null"]` I think the advantage of making it an optional property is that if there is no value, `quarantineUntil` does not needed to be included, rather than `"quarantineUntil": null`.
I haven't tested this change, but I'm hoping the CI will take care of this, or you'll be able to let me know if I need to do any additional testing.
Note: the motivation for making this change is because it broke the code generation in taskcluster-client-go. Until now, we never had a type that permitted multiple values. I could resolve this by enhancing taskcluster-client-go too (which I will probably do) but in discovering this, I saw it was inconsistent with the way we manage optional fields in the rest of the project, so …
=> Make property optional rather than returning null value

src/api.js, src/task-creds.js, src/workclaimer.js
I haven't run any tests locally, hoping travis will take care of that for me. :-)
Note, since auth now applies clock drift adjustment, this is also no longer necessary in the queue, so have removed that too.
Note, the temp credential naming schema I used is based on the scheme defined already in [our docs](https://github.com/taskcluster/taskcluster-docs/blob/ce34244bd65917485c2120e308c097c9ff5157b9/src/manual/design/namespaces.md#clients).
=> Bug 1249045 - issue named temporary credentials to tasks

package.json, src/api.js, yarn.lock
Upgrade taskcluster-lib-api version to the newest one. It is to
enable Access-Control-Max-Age, add name as options as it 
is required.
Related to Bug 1442636
@djmitche please review:D
=> Upgrade taskcluster-lib-api version

Procfile
Apparently Heroku's parsing of Procfiles is pretty generous..
=> Add colons where they belong in Procfile

package.json, yarn.lock
This brings in https://github.com/taskcluster/taskcluster-lib-api/pull/91
=> Bug 1449848 - Escape markdown (by upgrading tc-lib-api)

docs/task-life-cycle.md, docs/worker-interaction.md
The tools build process prefers this; otherwise, it doesn't really
matter..
=> Use relative links for svgs in docs

test/queueservice_test.js
If you want to take a look at the bug and fix the intermittency, we can re-enable when that's done..
=> Bug 1453514 - disable intermittent test

schemas/claim-work-response.yml, schemas/constants.yml, schemas/create-task-request.yml, schemas/list-workers-response.yml, schemas/list-workertypes-response.yml, schemas/pending-tasks-response.yml, schemas/post-artifact-request.yml, schemas/post-artifact-response.yml, schemas/task-claim-response.yml, schemas/task-credentials.yml, schemas/task-metadata.yml, schemas/task-reclaim-response.yml, schemas/task-run.yml, schemas/task.yml, schemas/worker-response.yml
This should be everything now. In total it reduces the schemas line count by 45 lines by removing duplication, which also removes the duplicated go types.
* I put common data structures into new files (`task-run.yml`, `task-credentials.yml`, `task-metadata.yml`) and `$ref` them
* Spelling correction: meta-data -> metadata
* Added missing titles that improve generated go code
* I made (`url`, `method`, `headers`) required properties, and disallowed additional properties, in Blob Artifact Response HTTP requests
* All tests pass 🕺
=> Hopefully last round of cleanup

schemas/artifact-created-message.yml, schemas/task-group-resolved.yml
This has the pleasant side effect of improving `tcqueueevents` generated types.
See [generated types](https://godoc.org/github.com/taskcluster/taskcluster-client-go/tcqueueevents) for context.
```
TaskGroupResolved1 -> TaskGroupResolvedMessage
ArtifactCreated1 -> Artifact
```
=> Adjust schema titles for consistency

src/api.js
Both are deprecated, part of the same process where workers interact
directly with Azure queues.
This also adds some docs for claimWork.
=> Mark claimTask and pollTaskUrls as deprecated

config.yml, src/api.js, src/artifacts.js, src/main.js
This includes renaming the env var to USE_CLOUD_MIRROR for consistency
with the JS name and removing the unused `usePublicArtifactBucketProxy`
configuration property.
Thanks to @jhford for most of this patch :)
---
I already added USE_CLOUD_MIRROR to the heroku config.
=> Bug 1478835 - fix support for useCloudMirror

schemas/constants.yml, src/api.js, test/createtask_test.js
The old solution used a negative lookbehind, which per
https://json-schema.org/understanding-json-schema/reference/regular_expressions.html#regular-expressions
is not supported in json-schema. In fact, it's not supported in even
fairly recent versions of Node. This causes problems when validating
schemas using those old versions of node (or using json-schema
validators that do not support this form).
So, the new solution is to explicitly forbid those forms where used in
creating clients and roles. The result is much the same, as evidenced
by the minimal changes to the tests.
=> Bug 1508849 - implement **-scope protection differently

src/api.js, test/createtask_test.js
This keeps with the maxim that you should check for permission as early as possible, before trusting any other data.  The user-visible change is that a task that is both invalid and not authorized will now result in an authorization error rather than an InputError.
Another approach may be to break `patchAndValidateTaskDef` into `patchTaskDef` and `validateTaskDef`.
=> Bug 1502892 - refactor create/defineTask to check authorization before validation
