taskcluster/taskcluster-queue

bin/server.js, config/defaults.js, config/production.js, config/test.js, package.json, queue/ec2regionresolver.js, routes/artifacts.js, routes/v1.js, test/api/artifact_test.js
We probably need more testing...
Like testing the actual proxies... at the very least...
Probably we can do testing of EC2 region hacks... by using x-forwarded-for in unit tests.
=> Add support for proxing for EC2 regions, and prod config

package.json, test/api/artifact_test.js, test/api/canceltask_test.js, test/api/claimtask_test.js, test/api/createtask_test.js, test/api/deadline_test.js, test/api/expiretask_test.js, test/api/gettask_test.js, test/api/minimumtask_test.js, test/api/polltask_test.js, test/api/querytasks_test.js, test/api/reportcompleted_test.js, test/api/reruntask_test.js, test/api/retry_test.js
@jhford, hi is this entirely crazy.... (probably).
Review is not really needed here.. .Just take a peak and see if you agree that `assume` beats `expect.js` in terms of being more modern and `should.js` by not poisoning the prototype.
I plan to use `assume` more extensively, so this is just as much a sanity check to hear what you think of the module?
=> Refactor test to use assume

queue/queueservice.js, test/queue/queueservice_test.js
Remove legacy queue names from bug 1170821...
=> Removed legacy queue creation

queue/data.js, queue/queueservice.js, routes/v1.js, schemas/create-task-request.yml, schemas/task.yml, test/api/gettask_test.js, test/api/minimumtask_test.js, test/api/polltask_test.js, test/api/priority_test.js, test/queue/queueservice_test.js, test/runtests.sh, test/validate_test/task.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1178877
=> Task priority

routes/artifacts.js, routes/v1.js
This should fix some issues with previous patch that I should have caught in review... or automated testing, unfortunately I'm human and travis is too buggy to trust...
=> Fixed scopes

test/api/priority_test.js
Looks sane to you ? just hit the merge button I pretty much trust this...
=> Fixed intermiettent test error

schemas/artifact-created-message.yml, schemas/constants.js, schemas/list-artifacts-response.yml, schemas/post-artifact-request.yml, schemas/task-exception-request.yml, schemas/task-status.yml, schemas/task.yml
=> Bug 1218913 - added missing type entries to schemas

bin/server.js, package.json, routes/artifacts.js, routes/v1.js, schemas/constants.js, schemas/task-claim-response.yml, schemas/task-reclaim-response.yml, schemas/task.yml, test/api/artifact_test.js, test/api/claimtask_test.js, test/api/helper.js, test/api/resolvetask_test.js
The interesting bits are in `v1.js` and `artifacts.js` + schema changes...
Read the docs in `constants.js` to see what the temp creds are for... Also this includes the task definition in return value from `claimTask`
=> Issue temp creds

routes/v1.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1228012
=> Added queue:worker-id:..

routes/v1.js, test/api/createtask_test.js, test/api/minimumtask_test.js, test/api/polltask_test.js, test/api/priority_test.js
very small changes... test pass so it should work...
I wanted to change scopes to require `scheduler-id`, but we since introduced some saner scopes...
So now I'm merging in the good things from this a branch, a bunch of small minor improvements...
=> Lock scheduler

queue/queueservice.js, routes/v1.js, test/api/querytasks_test.js
=> Remove pending tasks scope

config.yml, package.json, routes/v1.js, src/main.js, test/api/createtask_test.js, test/api/reruntask_test.js
This integrates the new raven/sentry stuff and adds a few new-style errors while I'm at it. If you want this in two reviews, just let me know and I'll split it out.
=> Sentry and newstyle

config.yml, routes/artifacts.js, src/main.js
@jonasfj : I would like to do short review cycles with you on these patches to
make sure this is done correctly.  Please let me know if using tags is a good
way to do this.  For creating jobs which would have the useCloudMirror tag, is
it just an extra entry into the tags dict when submitting the task/taskgraph?
=> Initial work for transitioning to cloud-mirror

src/main.js
=> Fix tabel typo

schemas/list-dependent-tasks-response.yml, src/api.js, src/data.js, src/main.js, test/dependency_test.js
This should enable us to list the dependents of a task...
=> List dependents

npm-shrinkwrap.json, src/api.js, src/queueservice.js, test/queueservice_test.js
This also bumps the versions of packages in shrinkwrap. I know we're being bad to do both at once, but what's the worst that could happen? 🔨
=> Add taskGroupId to taskResolved message queue messages

src/api.js, src/queueservice.js, test/queueservice_test.js
This is motivated by https://github.com/taskcluster/taskcluster-queue/pull/103#discussion_r72531794
=> Add task-group to deadline message as well

npm-shrinkwrap.json, package.json, src/api.js, src/queueservice.js, test/queueservice_test.js
As we discussed yesterday. I can also do a shrinkwrap update on this. Give me a sec to push that as well and we can deploy at once.
=> Add schedulerId to some azure message queues

schemas/task-group-resolved.yml, src/claimresolver.js, src/deadlineresolver.js, src/dependencyresolver.js, src/dependencytracker.js, src/exchanges.js, src/queueservice.js, test/queueservice_test.js, test/taskgroup_test.js
As we discussed in https://public.etherpad-mozilla.org/p/tc-task-group-queue-stuff
=> Start writing schedulerId in task-group-resolved

npm-shrinkwrap.json, package.json, src/claimresolver.js, src/deadlineresolver.js, src/dependencyresolver.js
As it says on the tin.
This also updates tc-base to be a version that includes lib-iterate for when we work on that.
=> Update monitor to not loop on failures

src/api.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1204898
=> Fix bug 1204898

src/api.js
See: https://sentry.io/taskcluster/taskcluster-queue/issues/158299920/
=> non-printable ascii in artifact names -> 400

schemas/task-exception-request.yml, schemas/task-status.yml, src/api.js, test/resolvetask_test.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1280570
=> Added intermittent-task reason for resolveException

src/main.js, src/scan.js
@jonasfj if you'd like to work your parallel-scanning trick in here, that'd be great.
=> Add a skeleton of task/s3 scanning support

schemas/constants.yml
Deadline exceeded is an exception not a failure...
=> Fixed wording of deadline description

src/queueservice.js
Let's not merge before we're ready to land #124
=> change some: var -> let

npm-shrinkwrap.json, test/artifact_test.js, test/blobstore_test.js, test/bucket_test.js, test/canceltask_test.js, test/claimtask_test.js, test/claimwork_test.js, test/createtask_test.js, test/deadline_test.js, test/expirequeues_test.js, test/expiretask_test.js, test/helper.js, test/polltask_test.js, test/priority_test.js, test/querytasks_test.js, test/queueservice_test.js, test/reruntask_test.js, test/resolvetask_test.js, test/retry_test.js, test/validate_test.js
New shrinkwrap as well.
@jonasfj @djmitche @imbstack r?
=> Eliminated tc-base from tests

src/main.js
=> Removing indirection

npm-shrinkwrap.json, package.json, src/main.js
=> Add tc-lib-docs

docs/task-life-cycle.md, docs/task-life-cycle.svg
More docs coming, this just a start...
=> Task life-cycle documentation

docs/queue-worker-interaction.svg, docs/worker-interaction.md
Maybe some if this is repetitive ramplings... and maybe I forgot something...
But hopefully it's better than nothing.
=> Added more docs on worker-queue interaction

src/artifacts.js, test/artifact_test.js
This will give consistently-formatted API errors.
=> use res.reportError instead of res.status

schemas/poll-task-urls-response.yml, schemas/task-exception-request.yml, src/api.js
As found in taskcluster/taskcluster-cli#100
=> fix spelling errors

src/main.js
This is how I broke queue for a minute today. My bad.
=> Add credentials to azure-entities

README.md
Just a nice-to-have that I noticed. Please merge if it makes sense to you.
=> Fix readme structure section

config.yml, schemas/create-task-request.yml, schemas/task.yml, src/api.js, src/data.js, src/queueservice.js, test/gettask_test.js, test/priority_test.js, test/queueservice_test.js
Please give this a detailed review... I was like 30% awake when I wrote 90% of this....
=> Implemented new priority levels

src/queueservice.js, src/workclaimer.js
Let's see if tests pass before we ship it...
=> More azure queue metrics

src/workclaimer.js
I probably should have tested that before I landed it........
=> Bug 1364121: use backticks to get interpolation

config.yml, schemas/list-provisioners-response.yml, src/api.js, src/data.js, src/main.js, src/workerinfo.js, test/helper.js, test/workerinfo_test.js
=> Bug 1384947 - track and list provisioners

package.json, schemas/update-worker-request.yml, schemas/worker-response.yml, src/api.js, src/data.js, src/workerinfo.js, test/workerinfo_test.js, yarn.lock
API endpoint to `GET` and `PUT` a worker
=> Bug 1390870 - Implement API endpoint for a worker

schemas/quarantine-worker-request.yml, schemas/worker-response.yml, src/data.js
This builds on #232 which did not catch all occurrences.
=> Make quarantineUntil an optional field, rather than allowing null value

schemas/constants.yml, schemas/poll-task-urls-response.yml, schemas/post-artifact-request.yml, schemas/post-artifact-response.yml, schemas/worker-response.yml
Let's wait for the CI to run on this before merging! I think I caught them all.
=> Bug 1431750 - add additionalProperties to schemas where missing

package.json, src/api.js, src/artifacts.js, yarn.lock
This probably won't be the first thing I'll land, but is indicative of the type of changes we'll make!
=> Update to new taskcluster-lib-api with scope expressions

package.json, yarn.lock
Shift taskcluster-queue to version 8.0.0 of tc-lib-api
=> upgrade taskcluster-lib-api to version 8.0.0

src/api.js
..just doing what the comment says!
=> Remove custom InputError definition, since lib-api supports it

src/api.js
We can use this to create alerts in signalfx, if some workerType isn't claiming work anymore...
=> Count claimWork calls

src/api.js, src/workerinfo.js, test/workerinfo_test.js
=> Bug 1434322 - return 404's when appropriate and always upsert upstream objects

schemas/actions.yml, schemas/constants.yml, schemas/list-provisioners-response.yml, schemas/provisioner-response.yml, schemas/update-provisioner-request.yml, schemas/worker-response.yml, schemas/workertype-response.yml
Hi guys!
I don't actually need three reviews - but I know all three of you might care about these changes, so requesting review from all of you in case you want to comment.
Note, you might want to wait for CI to complete before reviewing, as I'll be relying on it to gain assurance I've not broken anything.
Pete
=> Reduced duplication of actions in schemas, and updated titles and descriptions

schemas/actions.yml, schemas/worker-response.yml, schemas/workertype-response.yml
Seems I forgot to update these in #262.
=> Some extra changes missed in #262

schemas/list-dependent-tasks-response.yml, schemas/list-task-group-response.yml, schemas/task-definition-and-status.yml
=> Moved task definition and status into task-definition-and-status.yml

package.json, yarn.lock
This added `err.module = 'fast-azure-storage'` for errors that is caused by azure.
=> Force upgrade of fast-azure-storage

.taskcluster.yml, README.md, config.yml, package.json, src/main.js, yarn.lock
As it says on the tin.
~I'll try this out in prod tonight when there's low traffic.~
Nevermind, this causes the tests to fail it seems? Maybe it was caused by the azure-entities bump. I'll look into it tomorrow!
=> Allow logging azure timings

test/helper.js
Taskcluster-Github already does something like this.  The tables get
cleaned out and should have no rows at test completion, so this doesn't
use a lot of space.  There's no limit (aside from space) on the number
of tables in an account.
=> Bug 1509189 - use unique table names to avoid conflicts

package.json, src/bucket.js, yarn.lock
This gets all of our tests to pass! Just needed to get xml2js updated.
=> More monorepo fixes
